name: Build and Deploy

on:
 push:
   branch:
      - main
   pull_request:
      - main

stages:
  - test
  - build
  - deploy

jobs:
  include:
    # Run tests
    - stage: test
      script:
        - npm install
        - ng test

    # Build the project
    - stage: build
      script:
        - npm install
        - ng build --configuration production --output-path docs

    # Deploy to GitHub Pages
    - stage: deploy
      script:
        - npm install
        - echo Deploying to GitHub Pages...
        - ng deploy --base-href=/angular-project/ --repo=Rupesh-Darimisetti/task-tracker-angular-web-app

      run: npm install && npm run build && cp .\docs\index.html .\docs\404.html